import React from 'react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { FileText, Download, Printer } from 'lucide-react';
import { formatCurrency } from '@/services/mockDataService';

interface DocumentGeneratorProps {
  documentType: 'application' | 'risk-assessment' | 'approval' | 'rejection' | 'funding';
  applicationData: any;
  onClose?: () => void;
}

const DocumentGenerator: React.FC<DocumentGeneratorProps> = ({ 
  documentType, 
  applicationData,
  onClose
}) => {
  const generateDocument = () => {
    toast.info(`Generating ${documentType} document...`);
    
    setTimeout(() => {
      const win = window.open("", "_blank");
      if (!win) {
        toast.error("Unable to open a new window to display the document.");
        return;
      }
      
      const documentContent = renderDocumentContent();
      
      win.document.write(`
        <html>
          <head>
            <title>${getDocumentTitle()}</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 0; padding: 20px; color: #333; }
              .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
              .logo { max-width: 180px; }
              .document-title { font-size: 24px; font-weight: bold; margin-bottom: 5px; }
              .document-subtitle { font-size: 14px; color: #666; }
              h1 { color: #333; margin-top: 30px; }
              h2 { color: #444; margin-top: 25px; font-size: 18px; }
              .section { margin-bottom: 25px; }
              table { width: 100%; border-collapse: collapse; margin: 20px 0; }
              th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
              th { background-color: #f5f5f5; font-weight: bold; }
              .risk-high { color: #e11d48; }
              .risk-medium { color: #f59e0b; }
              .risk-low { color: #10b981; }
              .success { color: #10b981; }
              .warning { color: #f59e0b; }
              .error { color: #e11d48; }
              .signature { margin-top: 50px; border-top: 1px solid #ddd; padding-top: 20px; }
              .footer { margin-top: 50px; font-size: 12px; color: #666; text-align: center; }
              .watermark { position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-45deg); font-size: 100px; color: rgba(0,0,0,0.03); pointer-events: none; z-index: -1; }
              .badge { display: inline-block; padding: 3px 8px; border-radius: 12px; font-size: 12px; font-weight: bold; }
              .badge-success { background: #d1fae5; color: #065f46; }
              .badge-warning { background: #fef3c7; color: #92400e; }
              .badge-error { background: #fee2e2; color: #b91c1c; }
              ul { padding-left: 20px; }
              li { margin-bottom: 5px; }
              .highlight-box { background: #f9fafb; border: 1px solid #e5e7eb; padding: 15px; border-radius: 5px; margin: 15px 0; }
              @media print {
                .no-print { display: none; }
                body { padding: 0; }
                .watermark { display: none; }
              }
            </style>
          </head>
          <body>
            <div class="watermark">GaIgentic</div>
            <div class="header">
              <div>
                <div class="document-title">${getDocumentTitle()}</div>
                <div class="document-subtitle">Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
              </div>
              <img src="/lovable-uploads/c358cff4-5e06-49e8-af0b-d9e4c7099001.png" class="logo" alt="GaIgentic Logo">
            </div>
            
            <div class="no-print" style="text-align: right; margin-bottom: 20px;">
              <button onclick="window.print()" style="background: #f3f4f6; border: 1px solid #d1d5db; padding: 8px 16px; border-radius: 4px; cursor: pointer; margin-right: 10px;">
                Print Document
              </button>
              <button onclick="window.close()" style="background: #f3f4f6; border: 1px solid #d1d5db; padding: 8px 16px; border-radius: 4px; cursor: pointer;">
                Close
              </button>
            </div>
            
            ${documentContent}
            
            <div class="footer">
              <p>This document was automatically generated by GaIgentic Financial System.</p>
              <p>© ${new Date().getFullYear()} GaIgentic. All rights reserved.</p>
            </div>
            
            <script>
              document.addEventListener('DOMContentLoaded', function() {
                console.log('Document fully loaded and displayed');
              });
            </script>
          </body>
        </html>
      `);
      
      win.document.close();
      toast.success(`${getDocumentTitle()} generated successfully!`);
    }, 1500);
  };
  
  const getDocumentTitle = () => {
    switch (documentType) {
      case 'application':
        return 'Loan Application Summary';
      case 'risk-assessment':
        return 'Risk Assessment Report';
      case 'approval':
        return 'Loan Approval Letter';
      case 'rejection':
        return 'Application Decision Notice';
      case 'funding':
        return 'Funding Authorization Document';
      default:
        return 'Document';
    }
  };
  
  const renderDocumentContent = () => {
    switch (documentType) {
      case 'application':
        return renderApplicationSummary();
      case 'risk-assessment':
        return renderRiskAssessment();
      case 'approval':
        return renderApprovalLetter();
      case 'rejection':
        return renderRejectionLetter();
      case 'funding':
        return renderFundingDocument();
      default:
        return '<p>Document content not available.</p>';
    }
  };
  
  const renderApplicationSummary = () => {
    const { id, borrower, amount, purpose, dateSubmitted, status, assetClass, term, interestRate, collateral } = applicationData;
    
    const borrowerName = borrower.companyName || `${borrower.firstName} ${borrower.lastName}`;
    
    return `
      <div class="section">
        <h1>Loan Application Summary</h1>
        <p>Application ID: <strong>${id}</strong></p>
        
        <h2>Borrower Information</h2>
        <table>
          <tr>
            <th width="30%">Borrower Name</th>
            <td>${borrowerName}</td>
          </tr>
          <tr>
            <th>Contact Email</th>
            <td>${borrower.email || 'N/A'}</td>
          </tr>
          <tr>
            <th>Contact Phone</th>
            <td>${borrower.phone || 'N/A'}</td>
          </tr>
          <tr>
            <th>Address</th>
            <td>
              ${borrower.address ? 
                `${borrower.address.street}<br/>
                ${borrower.address.city}, ${borrower.address.state} ${borrower.address.zipCode}<br/>
                ${borrower.address.country}` : 'N/A'}
            </td>
          </tr>
          ${borrower.creditScore ? `
          <tr>
            <th>Credit Score</th>
            <td>${borrower.creditScore}</td>
          </tr>` : ''}
        </table>
        
        <h2>Loan Details</h2>
        <table>
          <tr>
            <th width="30%">Loan Amount</th>
            <td>${typeof amount === 'number' ? formatCurrency(amount) : amount}</td>
          </tr>
          <tr>
            <th>Purpose</th>
            <td>${purpose}</td>
          </tr>
          <tr>
            <th>Asset Class</th>
            <td>${assetClass.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}</td>
          </tr>
          <tr>
            <th>Term</th>
            <td>${term} months</td>
          </tr>
          ${interestRate ? `
          <tr>
            <th>Interest Rate</th>
            <td>${interestRate}%</td>
          </tr>` : ''}
          ${collateral ? `
          <tr>
            <th>Collateral</th>
            <td>
              <div>Type: ${collateral.type}</div>
              <div>Value: ${typeof collateral.value === 'number' ? formatCurrency(collateral.value) : collateral.value}</div>
              <div>Description: ${collateral.description}</div>
            </td>
          </tr>` : ''}
        </table>
        
        <h2>Application Status</h2>
        <div class="highlight-box">
          <p>Status: <span class="badge ${status === 'approved' || status === 'funded' ? 'badge-success' : 
                                        status === 'rejected' ? 'badge-error' : 'badge-warning'}">${
                                        status.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}</span></p>
          <p>Date Submitted: ${dateSubmitted || 'Not yet submitted'}</p>
          <p>Application Completion: ${applicationData.completeness}%</p>
        </div>
        
        ${applicationData.notes && applicationData.notes.length > 0 ? `
        <h2>Application Notes</h2>
        <table>
          ${applicationData.notes.map(note => `
            <tr>
              <td width="25%">${new Date(note.createdAt).toLocaleDateString()}</td>
              <td>${note.content}</td>
              <td width="20%">By: ${note.createdBy}</td>
            </tr>
          `).join('')}
        </table>
        ` : ''}
      </div>
      
      <div class="signature">
        <p>Document generated by GaIgentic Financial System</p>
        <p>Date: ${new Date().toLocaleDateString()}</p>
      </div>
    `;
  };
  
  const renderRiskAssessment = () => {
    const { id, borrower, risk, amount, purpose, assetClass, collateral, term, interestRate } = applicationData;
    
    const borrowerName = borrower.companyName || `${borrower.firstName} ${borrower.lastName}`;
    
    let riskLevel = 'Medium';
    let riskScore = 50;
    let riskFactors = [];
    let riskStrengths = [];
    let riskRatios = {};
    
    if (risk) {
      if (typeof risk === 'string') {
        riskLevel = risk;
      } else {
        riskLevel = risk.level || risk.rating || riskLevel;
        riskScore = risk.score || riskScore;
        riskFactors = risk.factors || [];
        riskStrengths = risk.strengths || [];
        riskRatios = risk.ratios || {};
      }
    }
    
    if (riskLevel === 'Low' && riskScore === 50) {
      riskScore = 85;
    } else if (riskLevel === 'High' && riskScore === 50) {
      riskScore = 20;
    }
    
    if (riskFactors.length === 0) {
      if (riskLevel === 'High') {
        riskFactors = [
          "Limited credit history or low credit score",
          "High debt-to-income ratio exceeding policy thresholds",
          "Unstable or insufficient income relative to loan size",
          "Insufficient collateral value or questionable collateral quality",
          "Industry sector experiencing significant volatility or decline",
          "Short time in business or irregular business operations"
        ];
      } else if (riskLevel === 'Medium') {
        riskFactors = [
          "Moderate credit history with some minor issues",
          "Debt-to-income ratio approaching policy limits",
          "Sufficient but not robust income stability",
          "Collateral value meets minimum requirements"
        ];
      }
    }
    
    if (riskStrengths.length === 0) {
      if (riskLevel === 'Low') {
        riskStrengths = [
          "Excellent credit score and payment history",
          "Strong and stable income stream",
          "Low debt-to-income ratio well within policy guidelines",
          "High-quality collateral with significant value margin",
          "Operation in a stable industry with positive growth outlook",
          "Extensive business experience and strong management team"
        ];
      } else if (riskLevel === 'Medium') {
        riskStrengths = [
          "Acceptable credit history with few late payments",
          "Stable income sufficient for loan payments",
          "Adequate collateral coverage",
          "Business demonstrating consistent performance"
        ];
      }
    }
    
    if (Object.keys(riskRatios).length === 0) {
      const loanToValueRatio = collateral && collateral.value ? 
        Math.round((amount / collateral.value) * 100) + '%' : 'N/A';
      
      const debtToIncomeRatio = borrower.income ?
        Math.round((((amount * (interestRate/1200)) / (1 - Math.pow(1 + (interestRate/1200), -term))) * 12 / borrower.income) * 100) + '%' :
        borrower.annualRevenue ?
        Math.round((((amount * (interestRate/1200)) / (1 - Math.pow(1 + (interestRate/1200), -term))) * 12 / borrower.annualRevenue) * 100) + '%' :
        'N/A';
      
      riskRatios = {
        "Loan-to-Value Ratio": loanToValueRatio,
        "Debt-to-Income Ratio": debtToIncomeRatio,
        "Debt Service Coverage Ratio": riskLevel === 'Low' ? '1.5' : riskLevel === 'Medium' ? '1.2' : '0.9',
        "Current Ratio": riskLevel === 'Low' ? '2.5' : riskLevel === 'Medium' ? '1.5' : '0.8'
      };
    }
    
    const industryAnalysis = borrower.industry ? 
      `<h2>Industry Sector Analysis</h2>
      <div class="highlight-box">
        <p>The ${borrower.industry} industry currently shows ${
          riskLevel === 'Low' ? 
            'strong growth potential with stable market conditions. Historical performance indicates resilience during economic downturns, and forward-looking indicators suggest continued stability.' : 
          riskLevel === 'Medium' ? 
            'moderate growth with some market fluctuations. The sector has shown adequate resilience historically, though it may experience some volatility in response to broader economic trends.' : 
            'significant volatility and sensitivity to market conditions. Recent sector performance has been inconsistent, with heightened sensitivity to economic downturns and regulatory changes.'
        }</p>
        <p><strong>Key Industry Factors:</strong></p>
        <ul>
          ${riskLevel === 'Low' ? `
            <li>Strong projected growth rate of 5-7% annually</li>
            <li>Limited regulatory concerns affecting operations</li>
            <li>Low competition intensity with strong market positioning</li>
            <li>Minimal exposure to international trade tensions</li>` : 
          riskLevel === 'Medium' ? `
            <li>Moderate projected growth rate of 3-4% annually</li>
            <li>Some regulatory changes on the horizon requiring monitoring</li>
            <li>Moderate competition with adequate market position</li>
            <li>Some exposure to supply chain or market disruptions</li>` : `
            <li>Uncertain growth prospects with potential for contraction</li>
            <li>Significant regulatory challenges affecting operations</li>
            <li>Intense competition threatening market position</li>
            <li>High vulnerability to external economic factors</li>`
          }
        </ul>
      </div>` : 
      '<p>No industry-specific analysis available for this application.</p>';
    
    const economicOutlook = `
      <h2>Economic Outlook Assessment</h2>
      <div class="highlight-box">
        <p>Current economic indicators suggest ${
          riskLevel === 'Low' ? 
            'a positive outlook for the lending environment. Interest rates are expected to remain stable, and economic growth forecasts are favorable.' : 
          riskLevel === 'Medium' ? 
            'a cautiously optimistic outlook with some potential risks. Interest rates may experience moderate fluctuations, and economic growth shows mixed signals.' : 
            'significant caution is warranted. Interest rate volatility is expected, and economic indicators suggest potential downside risks.'
        }</p>
        <p><strong>Key Macroeconomic Factors:</strong></p>
        <ul>
          ${riskLevel === 'Low' ? `
            <li>GDP growth trending positively at 2.5-3%</li>
            <li>Inflation remains within target range of 2-2.5%</li>
            <li>Unemployment rate stable at 3.5-4%</li>
            <li>Consumer confidence indices showing strength</li>` : 
          riskLevel === 'Medium' ? `
            <li>GDP growth moderate at 1.5-2%</li>
            <li>Inflation slightly above target at 3-3.5%</li>
            <li>Unemployment rate at 4.5-5%</li>
            <li>Consumer confidence showing mixed signals</li>` : `
            <li>GDP growth slowing to 0-1%</li>
            <li>Inflation above target at 4-5%</li>
            <li>Unemployment rate rising to 5.5-6%</li>
            <li>Consumer confidence trending downward</li>`
          }
        </ul>
      </div>`;
    
    const collateralAnalysis = collateral ? `
      <h2>Comprehensive Collateral Analysis</h2>
      <div class="highlight-box">
        <table>
          <tr>
            <th width="30%">Type</th>
            <td>${collateral.type}</td>
          </tr>
          <tr>
            <th>Value</th>
            <td>${typeof collateral.value === 'number' ? formatCurrency(collateral.value) : collateral.value}</td>
          </tr>
          <tr>
            <th>Loan-to-Value Ratio</th>
            <td>${typeof collateral.value === 'number' && typeof amount === 'number' ? 
                 `${Math.round((amount / collateral.value) * 100)}%` : 'N/A'}</td>
          </tr>
          <tr>
            <th>Description</th>
            <td>${collateral.description}</td>
          </tr>
        </table>
        <p><strong>Collateral Quality Assessment:</strong> ${
          riskLevel === 'Low' ? 
            'High-quality collateral with strong valuation supported by recent appraisals. The collateral has high liquidity and stable market value with minimal expected depreciation.' : 
          riskLevel === 'Medium' ? 
            'Adequate collateral with acceptable valuation. The collateral has reasonable liquidity, though some market fluctuations may affect future value.' : 
            'The collateral presents concerns regarding valuation stability and liquidity. Market conditions could significantly impact value, and liquidation may be challenging.'
        }</p>
      </div>` : 
      '<p>No collateral information available for this application.</p>';
    
    const stressTestingSection = `
      <h2>Financial Stress Testing</h2>
      <p>The application has been subjected to stress testing to assess resilience under adverse scenarios:</p>
      <table>
        <tr>
          <th>Scenario</th>
          <th>Impact Assessment</th>
          <th>Mitigation Factors</th>
        </tr>
        <tr>
          <td>Interest Rate Increase (+2%)</td>
          <td class="${riskLevel === 'Low' ? 'risk-low' : riskLevel === 'Medium' ? 'risk-medium' : 'risk-high'}">
            ${riskLevel === 'Low' ? 'Low Impact' : riskLevel === 'Medium' ? 'Moderate Impact' : 'Significant Impact'}
          </td>
          <td>
            ${riskLevel === 'Low' ? 
              'Borrower maintains substantial payment capacity even with increased rates.' : 
            riskLevel === 'Medium' ? 
              'Borrower can absorb moderate rate increases with some adjustment to cash flow.' : 
              'Borrower would face significant payment stress under increased rates.'}
          </td>
        </tr>
        <tr>
          <td>Income Reduction (-20%)</td>
          <td class="${riskLevel === 'Low' ? 'risk-low' : riskLevel === 'Medium' ? 'risk-medium' : 'risk-high'}">
            ${riskLevel === 'Low' ? 'Low Impact' : riskLevel === 'Medium' ? 'Moderate Impact' : 'High Impact'}
          </td>
          <td>
            ${riskLevel === 'Low' ? 
              'Strong cash reserves and multiple income sources provide substantial buffer.' : 
            riskLevel === 'Medium' ? 
              'Some cash reserves available, but prolonged income reduction would create strain.' : 
              'Limited reserves and high reliance on primary income source creates vulnerability.'}
          </td>
        </tr>
        <tr>
          <td>Collateral Value Decline (-15%)</td>
          <td class="${riskLevel === 'Low' ? 'risk-low' : riskLevel === 'Medium' ? 'risk-medium' : 'risk-high'}">
            ${riskLevel === 'Low' ? 'Low Impact' : riskLevel === 'Medium' ? 'Moderate Impact' : 'High Impact'}
          </td>
          <td>
            ${riskLevel === 'Low' ? 
              'Substantial equity cushion would remain even after value decline.' : 
            riskLevel === 'Medium' ? 
              'Adequate but reduced equity position would remain after decline.' : 
              'Minimal or negative equity position would result from value decline.'}
          </td>
        </tr>
      </table>`;
    
    return `
      <div class="section">
        <h1>Comprehensive Risk Assessment Report</h1>
        <p>Application ID: <strong>${id}</strong></p>
        <p>Generated by AI-Powered Risk Analysis System</p>
        
        <h2>Executive Summary</h2>
        <div class="highlight-box">
          <p>Overall Risk Rating: <span class="risk-${riskLevel.toLowerCase()}">${riskLevel} Risk</span></p>
          <p>Risk Score: ${riskScore}/100</p>
          <div style="background-color: #f0f0f0; height: 20px; width: 100%; border-radius: 10px; margin: 10px 0;">
            <div style="background-color: ${
              riskLevel.toLowerCase() === 'low' ? '#10b981' : 
              riskLevel.toLowerCase() === 'medium' ? '#f59e0b' : '#e11d48'
            }; height: 100%; width: ${riskScore}%; border-radius: 10px;"></div>
          </div>
          <p>${
            riskLevel === 'Low' ? 
            'This application presents a low risk profile with strong financial indicators, excellent credit history, and robust collateral. The application meets or exceeds all policy requirements for approval.' : 
            
            riskLevel === 'Medium' ? 
            'This application presents a moderate risk profile with generally acceptable financial indicators, adequate credit history, and sufficient collateral. Some areas require monitoring or enhanced terms, but the application falls within acceptable policy parameters.' : 
            
            'This application presents a high risk profile with multiple concerning indicators. Significant credit issues, insufficient financial capacity, or inadequate collateral create substantial repayment risk that exceeds standard policy tolerance.'
          }</p>
        </div>
        
        <h2>Application Overview</h2>
        <table>
          <tr>
            <th width="30%">Borrower</th>
            <td>${borrowerName}</td>
          </tr>
          <tr>
            <th>Loan Amount</th>
            <td>${typeof amount === 'number' ? formatCurrency(amount) : amount}</td>
          </tr>
          <tr>
            <th>Purpose</th>
            <td>${purpose}</td>
          </tr>
          <tr>
            <th>Asset Class</th>
            <td>${assetClass.replace(/_/g, ' ').replace(/\\b\\w/g, l => l.toUpperCase())}</td>
          </tr>
          <tr>
            <th>Term</th>
            <td>${term} months</td>
          </tr>
          <tr>
            <th>Interest Rate</th>
            <td>${interestRate}%</td>
          </tr>
          ${borrower.creditScore ? `
          <tr>
            <th>Credit Score</th>
            <td>${borrower.creditScore} ${borrower.creditRating ? `(${borrower.creditRating})` : ''}</td>
          </tr>` : ''}
          ${borrower.income ? `
          <tr>
            <th>Annual Income</th>
            <td>${typeof borrower.income === 'number' ? formatCurrency(borrower.income) : borrower.income}</td>
          </tr>` : ''}
          ${borrower.annualRevenue ? `
          <tr>
            <th>Annual Revenue</th>
            <td>${typeof borrower.annualRevenue === 'number' ? formatCurrency(borrower.annualRevenue) : borrower.annualRevenue}</td>
          </tr>` : ''}
        </table>
        
        <h2>Borrower Risk Profile</h2>
        <div class="highlight-box">
          <p><strong>Credit History: </strong>${
            riskLevel === 'Low' ? 
              'Excellent credit history with no derogatory items. Consistent on-time payment history across all credit obligations.' : 
            riskLevel === 'Medium' ? 
              'Generally good credit history with minor derogatory items. Mostly on-time payments with occasional late payments.' : 
              'Problematic credit history with significant derogatory items. Pattern of late payments or defaults on credit obligations.'
          }</p>
          
          <p><strong>Financial Capacity: </strong>${
            riskLevel === 'Low' ? 
              'Strong financial capacity with substantial income relative to obligations. Multiple income sources provide stability and buffer against unexpected events.' : 
            riskLevel === 'Medium' ? 
              'Adequate financial capacity with sufficient income to meet obligations. Income sources are relatively stable but with limited buffer for unexpected events.' : 
              'Limited financial capacity with income barely sufficient or insufficient to meet obligations. Income sources may be unstable or highly dependent on variable factors.'
          }</p>
          
          <p><strong>Stability Indicators: </strong>${
            riskLevel === 'Low' ? 
              borrower.employmentInfo ? 
                `Long-term employment (${new Date().getFullYear() - new Date(borrower.employmentInfo.startDate).getFullYear()} years) in a stable industry with strong job security.` : 
                borrower.yearsInBusiness ? 
                  `Well-established business with ${borrower.yearsInBusiness} years of operation and demonstrated resilience.` : 
                  'Strong stability indicators with established history.' : 
            riskLevel === 'Medium' ? 
              borrower.employmentInfo ? 
                `Moderate employment tenure (${new Date().getFullYear() - new Date(borrower.employmentInfo.startDate).getFullYear()} years) in a relatively stable position.` : 
                borrower.yearsInBusiness ? 
                  `Established business with ${borrower.yearsInBusiness} years of operation showing adequate performance.` : 
                  'Acceptable stability indicators with reasonable history.' : 
              borrower.employmentInfo ? 
                `Limited employment history (${new Date().getFullYear() - new Date(borrower.employmentInfo.startDate).getFullYear()} years) or position in volatile industry.` : 
                borrower.yearsInBusiness ? 
                  `Relatively new business with only ${borrower.yearsInBusiness} years of operation and limited track record.` : 
                  'Concerning stability indicators with limited history or high volatility.'
          }</p>
        </div>
        
        <h2>Key Risk Factors</h2>
        ${riskFactors.length > 0 ? `
        <ul>
          ${riskFactors.map(factor => `<li>${factor}</li>`).join('')}
        </ul>
        ` : '<p>No specific risk factors identified.</p>'}
        
        <h2>Key Strengths</h2>
        ${riskStrengths.length > 0 ? `
        <ul>
          ${riskStrengths.map(strength => `<li>${strength}</li>`).join('')}
        </ul>
        ` : '<p>No specific strengths highlighted.</p>'}
        
        ${Object.keys(riskRatios).length > 0 ? `
        <h2>Financial Ratios & Metrics</h2>
        <table>
          ${Object.entries(riskRatios).map(([key, value]) => `
            <tr>
              <th width="40%">${key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase())}</th>
              <td>${value}</td>
            </tr>
          `).join('')}
        </table>
        ` : ''}
        
        ${industryAnalysis}
        
        ${economicOutlook}
        
        ${collateralAnalysis}
        
        ${stressTestingSection}
        
        <h2>AI Risk Analysis Conclusion</h2>
        <p>${
          riskLevel === 'Low' ? 
          'Based on our comprehensive AI-powered risk assessment analysis, this application presents a low risk profile. The borrower demonstrates strong financial stability, excellent credit history, and the loan purpose aligns well with our lending criteria. The collateral valuation is robust, and market conditions are favorable for this type of financing.' : 
          
          riskLevel === 'Medium' ? 
          'Based on our comprehensive AI-powered risk assessment analysis, this application presents a moderate risk profile. While there are some areas of concern, these are balanced by positive aspects of the borrower\'s profile and application. Additional monitoring or modifications to standard terms may be warranted. The collateral provides adequate coverage, though market conditions show some volatility that could impact the borrower\'s repayment capacity.' : 
          
          'Based on our comprehensive AI-powered risk assessment analysis, this application presents a high risk profile. Several significant risk factors have been identified that require careful consideration. The current market conditions and industry outlook compound the inherent risks in this proposal. This application would require substantial mitigating factors, additional collateral, guarantees, or significant modifications to terms before approval could be considered.'
        }</p>
        
        <h2>Recommendation</h2>
        <div class="highlight-box">
          <p><strong>Primary Recommendation: </strong>${
            riskLevel === 'Low' ? 
            'Approval with standard terms' : 
            
            riskLevel === 'Medium' ? 
            'Conditional approval with enhanced monitoring and modified terms' : 
            
            'Decline or require significant restructuring before reconsideration'
          }</p>
          
          <p><strong>Suggested Loan Structure: </strong>${
            riskLevel === 'Low' ? 
            `Standard ${term}-month term at ${interestRate}% interest rate with normal monitoring requirements.` : 
            
            riskLevel === 'Medium' ? 
            `${term}-month term at ${interestRate + 0.5}% interest rate with quarterly financial reporting and enhanced monitoring.` : 
            
            `If pursued, would require substantial restructuring: reduced loan amount (maximum ${formatCurrency(amount * 0.7)}), higher interest rate (${interestRate + 1.5}% minimum), additional collateral requirements, and personal guarantees.`
          }</p>
          
          <p><strong>Policy Exceptions Required: </strong>${
            riskLevel === 'Low' ? 
            'None - application meets all standard policy requirements.' : 
            
            riskLevel === 'Medium' ? 
            'Minor exceptions to standard policy may be required concerning the debt-to-income ratio or collateral coverage.' : 
            
            'Major exceptions to multiple policy requirements would be necessary to proceed with this application.'
          }</p>
        </div>
      </div>
      
      <div class="signature">
        <p>Risk assessment conducted by GaIgentic AI Underwriting System</p>
        <p>Date: ${new Date().toLocaleDateString()}</p>
        <p>Analysis ID: RA-${Math.random().toString(36).substr(2, 9).toUpperCase()}</p>
      </div>
    `;
  };
  
  const renderApprovalLetter = () => {
    const { id, borrower, amount, purpose, term, interestRate } = applicationData;
    
    const borrowerName = borrower.companyName || `${borrower.firstName} ${borrower.lastName}`;
    
    return `
      <div class="section">
        <h1>Loan Approval Letter</h1>
        <p style="margin-bottom: 30px;">Date: ${new Date().toLocaleDateString()}</p>
        
        <p>Dear ${borrowerName},</p>
        
        <p>We are pleased to inform you that your loan application (ID: <strong>${id}</strong>) has been <span class="success">APPROVED</span>.</p>
        
        <h2>Approved Loan Terms</h2>
        <table>
          <tr>
            <th width="30%">Loan Amount</th>
            <td>${typeof amount === 'number' ? formatCurrency(amount) : amount}</td>
          </tr>
          <tr>
            <th>Purpose</th>
            <td>${purpose}</td>
          </tr>
          <tr>
            <th>Loan Term</th>
            <td>${term} months</td>
          </tr>
          <tr>
            <th>Interest Rate</th>
            <td>${interestRate}%</td>
          </tr>
          <tr>
            <th>Estimated Monthly Payment</th>
            <td>${formatCurrency((amount * (interestRate/1200)) / (1 - Math.pow(1 + (interestRate/1200), -term)))}</td>
          </tr>
        </table>
        
        <h2>Next Steps</h2>
        <ol>
          <li>Review and sign the attached loan agreement documents</li>
          <li>Provide any additional documentation required for closing</li>
          <li>Schedule an appointment with your loan officer to complete the process</li>
        </ol>
        
        <div class="highlight-box">
          <p>Important: This approval is valid for 30 days from the date of this letter. If the loan is not closed within this period, we reserve the right to review and potentially adjust the terms based on current market conditions.</p>
        </div>
        
        <p style="margin-top: 30px;">Congratulations on your loan approval. We look forward to helping you achieve your financial goals. Should you have any questions or require further assistance, please do not hesitate to contact your relationship manager.</p>
        
        <p style="margin-top: 30px;">Sincerely,</p>
        <p style="margin-top: 50px;">GaIgentic Financial Team</p>
      </div>
    `;
  };
  
  const renderRejectionLetter = () => {
    const { id, borrower, amount, purpose } = applicationData;
    
    const borrowerName = borrower.companyName || `${borrower.firstName} ${borrower.lastName}`;
    
    return `
      <div class="section">
        <h1>Application Decision Notice</h1>
        <p style="margin-bottom: 30px;">Date: ${new Date().toLocaleDateString()}</p>
        
        <p>Dear ${borrowerName},</p>
        
        <p>Thank you for your recent loan application (ID: <strong>${id}</strong>) for ${typeof amount === 'number' ? formatCurrency(amount) : amount} for the purpose of ${purpose}.</p>
        
        <p>After careful consideration and a thorough review of your application, we regret to inform you that we are unable to approve your loan request at this time.</p>
        
        <h2>Factors Considered in Our Decision</h2>
        <ul>
          <li>Credit history and current credit obligations</li>
          <li>Income verification and debt-to-income ratio analysis</li>
          <li>Collateral valuation and loan-to-value assessment</li>
          <li>Industry and market risk factors</li>
        </ul>
        
        <div class="highlight-box">
          <p>You have the right to request specific reasons for our decision within 60 days. You may also request a copy of the credit report we used in our evaluation.</p>
        </div>
        
        <h2>Alternative Options</h2>
        <p>We encourage you to consider the following alternatives:</p>
        <ul>
          <li>Apply for a different loan product that may better suit your current financial situation</li>
          <li>Work with our financial advisors to strengthen your application for future consideration</li>
          <li>Explore partnership opportunities with our small business development team</li>
        </ul>
        
        <p style="margin-top: 30px;">We value your interest in GaIgentic Financial and would be happy to discuss alternative financing options or ways to improve your future applications. Please contact our customer service team to schedule a consultation.</p>
        
        <p style="margin-top: 30px;">Sincerely,</p>
        <p style="margin-top: 50px;">GaIgentic Financial Team</p>
      </div>
    `;
  };
  
  const renderFundingDocument = () => {
    const { id, borrower, amount, purpose, dateApproved = new Date().toLocaleDateString(), term, interestRate } = applicationData;
    
    const borrowerName = borrower.companyName || `${borrower.firstName} ${borrower.lastName}`;
    
    return `
      <div class="section">
        <h1>Funding Authorization Document</h1>
        <p>Application ID: <strong>${id}</strong></p>
        
        <div class="highlight-box">
          <h2 style="margin-top: 0;">Funding Authorization</h2>
          <p>This document authorizes the disbursement of funds for the approved loan application referenced above.</p>
          <p>Authorization Date: ${new Date().toLocaleDateString()}</p>
          <p>Funding Status: <span class="badge badge-success">Approved for Disbursement</span></p>
        </div>
        
        <h2>Loan Details</h2>
        <table>
          <tr>
            <th width="30%">Borrower</th>
            <td>${borrowerName}</td>
          </tr>
          <tr>
            <th>Approved Amount</th>
            <td>${typeof amount === 'number' ? formatCurrency(amount) : amount}</td>
          </tr>
          <tr>
            <th>Purpose</th>
            <td>${purpose}</td>
          </tr>
          <tr>
            <th>Approval Date</th>
            <td>${dateApproved}</td>
          </tr>
          <tr>
            <th>Loan Term</th>
            <td>${term} months</td>
          </tr>
          <tr>
            <th>Interest Rate</th>
            <td>${interestRate}%</td>
          </tr>
        </table>
        
        <h2>Disbursement Information</h2>
        <table>
          <tr>
            <th width="30%">Method of Disbursement</th>
            <td>Electronic Fund Transfer</td>
          </tr>
          <tr>
            <th>Scheduled Disbursement Date</th>
            <td>${new Date(new Date().setDate(new Date().getDate() + 2)).toLocaleDateString()}</td>
          </tr>
          <tr>
            <th>Disbursement Amount</th>
            <td>${typeof amount === 'number' ? formatCurrency(amount) : amount}</td>
          </tr>
        </table>
        
        <h2>Terms and Conditions</h2>
        <ul>
          <li>Funds will be disbursed to the account specified in the loan agreement</li>
          <li>First payment due 30 days after disbursement</li>
          <li>All conditions precedent have been satisfied</li>
          <li>Loan documents have been properly executed and recorded where applicable</li>
        </ul>
        
        <div class="highlight-box">
          <p><strong>Important Notice:</strong> This funding authorization is valid for 5 business days from the authorization date. If disbursement cannot be completed within this timeframe, a new authorization will be required.</p>
        </div>
      </div>
      
      <div style="margin-top: 50px;">
        <p style="border-top: 1px solid #ddd; padding-top: 20px;">Authorized by: GaIgentic Financial Funding Department</p>
        <p>Authorization ID: FND-${Math.random().toString(36).substring(2, 10).toUpperCase()}</p>
        <p>Date: ${new Date().toLocaleDateString()}</p>
      </div>
    `;
  };

  return (
    <div className="flex flex-col space-y-2">
      <Button onClick={generateDocument} className="w-full">
        <FileText className="mr-2 h-4 w-4" />
        Generate {getDocumentTitle()}
      </Button>
      
      <div className="flex gap-2">
        <Button variant="outline" className="flex-1">
          <Download className="mr-2 h-4 w-4" />
          Save PDF
        </Button>
        <Button variant="outline" className="flex-1">
          <Printer className="mr-2 h-4 w-4" />
          Print
        </Button>
      </div>
    </div>
  );
};

export default DocumentGenerator;
